[project]
name = "marimo-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.7",
    "numpy",
    "duckdb",
    "sentence-transformers",
    "python-dotenv",
    "google-generativeai",
]

[tool.uv]
